# Site settings
title: Lu Xiang
email: lx2000v@gmial.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lu-xiang.cc" # the base hostname & protocol for your site

# Build settings
markdown: kramdown